### ISSUE TITLE
Migrate from mocha to karma for running backend tests

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/squardak#10]
Mocha sucks.

**Comment by BlookHo** [comment]
Hi! I remember, you had used Karma before. So, why did you decide to start with Mocha?
And why Mocha was defeated by Karma in your battle? ) (Shortly)

**Comment by cbrwizard** [comment]
@BlookHo hey, I didn't enjoy using Mocha because I was having issues with errors handling there and the configuration options were scarce, also I had troubles getting it to work with latest ES6.
It turned out that Karma works only for frontend specs, so that didn't work out. I switched to ava.js instead https://github.com/avajs/ava which just works.
